markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]
highlighter: rouge

exclude: [old]
permalink: pretty
relative_permalinks: true

title: 'KentProjects'
tagline: 'Documentation for an API'